config/routes.rb
Rails.application.routes.draw do

  # API
  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      resources :players, only: [:index, :show]
			resources :towns, only: [:index, :show]
	    resources :alliances, only: [:index, :show]
      resources :conquers, only: [:index, :show]
    end
  end

  # //
  root 'pages#home'

  # Devise 
  devise_for :users, path: '',
    path_names: {sign_in: 'login', sign_out: 'logout', sign_up: 'register'}

  # get '*path', to: 'pages#home'

  # Players 
	resources :players, only: [:index, :show] do
    member do
      get :follow
      get :unfollow
    end
  end

	resources :towns, only: [:index, :show]
	resources :alliances, only: [:index, :show]
  resources :conquers, only: [:index, :show]


  # Public Activity
  resources :activities
  get 'clear_activities' => 'activities#delete_all', as: :clear_activities

end

app/models/alliance.rb
class Alliance < ActiveRecord::Base

	self.primary_key = 'grepo_id'
	has_many :players

end

app/models/conquer.rb
class Conquer < ActiveRecord::Base

	# Primary Key
  # self.primary_key = 'town_id'

  # Associations
  belongs_to :town, foreign_key: :town_id
  belongs_to :player, foreign_key: :new_player_id, touch: true
  belongs_to :old_player, class_name: 'Player', foreign_key: :old_player_id
  belongs_to :old_alliance, class_name: 'Alliance', foreign_key: :old_ally_id

  # Public Activity
  include PublicActivity::Common

  def conquer_time
    Time.at(self.time).strftime('%d-%m-%Y, %H:%M')
  end

end

app/models/follow.rb
class Follow < ActiveRecord::Base

  extend ActsAsFollower::FollowerLib
  extend ActsAsFollower::FollowScopes

  # NOTE: Follows belong to the "followable" interface, and also to followers
  belongs_to :followable, :polymorphic => true
  belongs_to :follower,   :polymorphic => true

  def block!
    self.update_attribute(:blocked, true)
  end

end

app/models/player.rb
class Player < ActiveRecord::Base
  
  # Public Activity
  include PublicActivity::Common
  
  # Primary Key
	self.primary_key = 'grepo_id'

  # Associations
	has_many :towns
	belongs_to :alliance, touch: true
  has_many :conquers, class_name: 'Conquer', foreign_key: :new_player_id

  # Followable
  acts_as_followable

end

app/models/town.rb
class Town < ActiveRecord::Base
  
  # Primary Key
	self.primary_key = 'grepo_id'

  # Associations
  belongs_to :player, foreign_key: :player_id, touch: true
  has_many :conquers, foreign_key: :town_id

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Follower
  acts_as_follower

end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController

  before_action :authenticate_user!
  
  def index
    @activities = PublicActivity::Activity.where(recipient: current_user).order("created_at desc")
  end

  def delete_all
  	PublicActivity::Activity.where(recipient: current_user).delete_all
  	redirect_to :back
  end

end

app/controllers/alliances_controller.rb
class AlliancesController < ApplicationController
  def index
  end

  def show
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  # Public Activity
  include PublicActivity::StoreController

  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

   def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << []
    devise_parameter_sanitizer.for(:account_update) << []
  end 

end

app/controllers/conquers_controller.rb
class ConquersController < ApplicationController

	# def update
	#  	# Create Activities
 #    # --> Goes out to every User that subscribed to the Player that Conquered (new_player_id)
 #    if @owner = Player.find(params[:new_player_id]).present?
 #      if @owner.followers.count > 0
 #        @conquer.create_activity :create, recipient: @owner.followers
 #      end
 #    end
	# end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  def index
		@players = Player.all.order("rank asc").paginate(:page => params[:page], :per_page => 30)
  end

  def show
		@player = Player.find(params[:id])
  end

  def follow
    @player = Player.find(params[:id])
    current_user.follow(@player)
    redirect_to :back
  end

  def unfollow
    @player = Player.find(params[:id])
    current_user.stop_following(@player)
    # Delete Activities that have been created
    PublicActivity::Activity.where(owner: @player, recipient: current_user).delete_all
    redirect_to :back
  end

end

app/controllers/towns_controller.rb
class TownsController < ApplicationController
  def index
  end

  def show
  end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/alliances_helper.rb
module AlliancesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/conquers_helper.rb
module ConquersHelper

  # Intern Conquer
  def intern_conquer(c)
    (if c.intern
      "<i class='fa fa-check-circle' style='color: rgba(46, 204, 113, 0.6);'></i>"
    else
      "<i class='fa fa-circle' style='color: rgba(165,182,199,0.4)'></i>" 
    end).html_safe
  end

end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/players_helper.rb
module PlayersHelper

  def follow_button(player)
    if user_signed_in?
      if current_user.following?(player)
        link_to unfollow_player_path(player), class: 'GrepoliaButton' do
          "<i class='fa fa-check-square-o'></i> &nbsp; Following".html_safe
        end
      else
        link_to follow_player_path(player), class: 'GrepoliaButton' do
          "<i class='fa fa-square-o'></i> &nbsp; Follow".html_safe
        end
      end
    end
  end

end

app/helpers/towns_helper.rb
module TownsHelper
end

app/views/layouts/_header.html.haml
%nav.navbar.navbar-default.navbar-fixed-top.grepolia-nav{:role => "navigation"}
  .container
    / Brand and toggle get grouped for better mobile display
    .navbar-header
      %button.navbar-toggle{"data-target" => "#navbar-brand-centered", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      .navbar-brand.navbar-brand-centered 
        =link_to 'Grepolia', root_path

    / Collect the nav links, forms, and other content for toggling
    #navbar-brand-centered.collapse.navbar-collapse
      %ul.nav.navbar-nav
        %li
          =link_to players_path do
            %i.fa.fa-users
            Players
        %li
          =link_to alliances_path do
            %i.fa.fa-shield
            Alliances
      %ul.nav.navbar-nav.navbar-right
        - if user_signed_in?
          %li
            =link_to activities_path do
              %i.fa.fa-dot-circle-o
              Activities 
          %li
            =link_to edit_user_registration_path do
              %i.fa.fa-sliders
              Settings
          %li
            =link_to destroy_user_session_path, method: :delete do
              %i.fa.fa-power-off 
              Log out
        - else
          %li
            =link_to new_user_session_path do
              %i.fa.fa-power-off
              Sign in

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Grepolia</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= stylesheet_link_tag 'application', media: 'all' %> 
  <%= stylesheet_link_tag '//cdnjs.cloudflare.com/ajax/libs/font-awesome/4.1.0/css/font-awesome.min.css', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/header' %>

<div class="container">
  <% flash.each do |name, msg| %>
    <%= content_tag(:div, class: "alert alert-info") do %>
      <%= msg %>
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
          <i class="fa fa-minus-square"></i>
        </button>
    <% end %>
  <% end %>

  <%= yield %>
</div>

</body>
</html>

app/views/pages/home.html.haml
- if user_signed_in?
  .jumbotron.center
    %h1 Welcome to Grepolia
    %p
      = link_to 'Log in', '#', class: 'btn btn-primary'
      = link_to 'Sign up', '#', class: 'btn btn-default'
- else
  #app-mount-point